FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY prisma ./prisma/
RUN npx prisma generate

RUN npm prune --omit=dev

COPY . .

EXPOSE 3000 3001

CMD ["node", "src/server.js"]
